# Challenge - Cars ðŸš™

Let's practice our new skills with a dataset listing cars models.

**Q1**. Begin by importing pandas and numpy using the standard convention:

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
# TODO: Import numpy and pandas with the right convention
import numpy as np
import pandas as pd

**Q2**. Now load the file `input/automobile_data.csv` into the **DataFrame** `cars_df` and display the first lines:

In [7]:
# TODO: load the dataset contained in the file automobile_data.csv
cars_df = pd.read_csv("/content/drive/MyDrive/datasets/automobile_data.csv")
cars_df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

**Q3**. Do you see any missing or strange data?

Reload the automobile data into a `cars_df` DataFrame and make sure this time to treat those strange values as `NaN`.

In [8]:
#Â TODO: identify how the missing data is filled and replace it with NaN
# and then display again the first ten lines to check it has worked
cars_df.replace("?",np.nan, inplace=True)
cars_df.head(n=10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,NaN

**Q4**. Display the last 8 rows of the DataFrame.

In [10]:
# TODO: display the last 8 rows of cars
cars_df.tail(n=8)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

**Q5**. What is the **shape** of this DataFrame (number of lines, number of columns)?

In [13]:
# TODO: Get shape of the DataFrame
print(f"The DataFtrame has {cars_df.shape[0]} rows and {cars_df.shape[1]} features")

The DataFtrame has 205 rows and 26 features

**Q6**. Retrieve the number of non null entries per column. Does the column price contain null values?

In [42]:
# TODO: Print out the information of the dataframe
cars_df.info()
#cars_df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       203 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               201 non-null    object
 19  stroke             201 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    object
 22  peak-rpm           203 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB


*   *The columns price, bore, stroke have 4 null values each*

*   *The columns num-of-doors,horsepower, peak-rpm have 2 null values each*


*   *The column normalized-losses has 41 null values*

**Q7**. Let's now select all the rows with a value in 'price' column, and store them it in a new DataFrame called `cars_with_price_df`.

What is the shape of this new DataFrame? Confirm your answer using previous result.

In [21]:
# TODO: select the cars with a price in the variable cars_with_price
cars_with_price_df = cars_df[cars_df["price"].notnull()]
cars_with_price_df.shape

(201, 26)

**Q8**. How many distinct `constructors` exist in the dataset?

In [23]:
# TODO: print how many mobile constructors ('make') are present in the dataset
print(f" There is {cars_df['make'].nunique()} mobile constructors")

 There is 22 mobile constructors

**Q9**. Display all the constructors that have released more than 10 models. Save those results into a new `big_makers` variable.

In [36]:
# TODO: Which makers have more than 10 models?



nb_models_per_maker = cars_df['make'].value_counts()

big_makers = nb_models_per_maker.loc[nb_models_per_maker > 10]
big_makers

toyota        32
nissan        18
mazda         17
mitsubishi    13
honda         13
volkswagen    12
subaru        12
peugot        11
volvo         11
Name: make, dtype: int64

**Q10**. Let's order a bit those results:
- Fist, display those results in alphabetical order
- Secondly, display those results by increasing value of number of models

In [40]:
# TODO: Sort the results
print("Results in alphabetical order", big_makers.sort_index())

print("\n Results by increasing value of number of models \n",big_makers.sort_values(ascending=True))

Results in alphabetical order honda         13
mazda         17
mitsubishi    13
nissan        18
peugot        11
subaru        12
toyota        32
volkswagen    12
volvo         11
Name: make, dtype: int64

 Results by increasing value of number of models
 peugot        11
volvo         11
volkswagen    12
subaru        12
mitsubishi    13
honda         13
mazda         17
nissan        18
toyota        32
Name: make, dtype: int64

**Q11**. Retrieve the following statistics:
- the car with the maximum horsepower
- the car with the minimum length
- the mean of cars width
- the standard deviation of cars height

In [55]:
# TODO: Print various statistics

cars_df['horsepower'] = pd.to_numeric(cars_df['horsepower'], errors='coerce')


max_horsepower = cars_df['horsepower'].max()
car_max_horsepower = cars_df[cars_df['horsepower']== max_horsepower]

print(f"The maximum horsepower  is {max_horsepower}")

print("The minimum length" ,cars_df['length'].min())
print("The mean of the car width" ,cars_df['width'].mean())
print("The  standard deviation of cars height" ,cars_df['height'].std())

The maximum horsepower  is 288.0
The minimum length 141.1
The mean of the car width 65.90780487804878
The  standard deviation of cars height 2.4435219699049036